### ISSUE TITLE
cannot open eaf-music-player

### ISSUE THREAD

**Issue by ententent** [emacs-eaf/eaf-music-player#25]
Traceback (most recent call last):
  File "/home/mawen/.emacs.d/site-lisp/emacs-application-framework/app/music-player/buffer.py", line 107, in init_app
    self.music_infos = self.pick_music_info(files)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mawen/.emacs.d/site-lisp/emacs-application-framework/app/music-player/buffer.py", line 146, in pick_music_info
    "name": self.pick_tag_title(tags),
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mawen/.emacs.d/site-lisp/emacs-application-framework/app/music-player/buffer.py", line 129, in pick_tag_title
    return tags["TITLE"][0].strip() if "TITLE" in tags and len(tags["TITLE"]) > 0 else os.path.splitext(os.path.basename(file))[0]
                                                                                                                         ^^^^
NameError: name 'file' is not defined. Did you mean: 'filter'?

Process *eaf* 已放弃 (core dumped)

**Comment by manateelazycat** [comment]
Has fixed
